/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClickRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7697623325931867572L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClickRecord\",\"fields\":[{\"name\":\"Description\",\"type\":\"string\"},{\"name\":\"Quantity\",\"type\":[\"string\",\"null\"]},{\"name\":\"UnitPrice\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClickRecord> ENCODER =
      new BinaryMessageEncoder<ClickRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClickRecord> DECODER =
      new BinaryMessageDecoder<ClickRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ClickRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ClickRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClickRecord>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ClickRecord to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ClickRecord from a ByteBuffer. */
  public static ClickRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence Description;
  @Deprecated public java.lang.CharSequence Quantity;
  @Deprecated public java.lang.CharSequence UnitPrice;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClickRecord() {}

  /**
   * All-args constructor.
   * @param Description The new value for Description
   * @param Quantity The new value for Quantity
   * @param UnitPrice The new value for UnitPrice
   */
  public ClickRecord(java.lang.CharSequence Description, java.lang.CharSequence Quantity, java.lang.CharSequence UnitPrice) {
    this.Description = Description;
    this.Quantity = Quantity;
    this.UnitPrice = UnitPrice;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Description;
    case 1: return Quantity;
    case 2: return UnitPrice;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Description = (java.lang.CharSequence)value$; break;
    case 1: Quantity = (java.lang.CharSequence)value$; break;
    case 2: UnitPrice = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Description' field.
   * @return The value of the 'Description' field.
   */
  public java.lang.CharSequence getDescription() {
    return Description;
  }

  /**
   * Sets the value of the 'Description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.Description = value;
  }

  /**
   * Gets the value of the 'Quantity' field.
   * @return The value of the 'Quantity' field.
   */
  public java.lang.CharSequence getQuantity() {
    return Quantity;
  }

  /**
   * Sets the value of the 'Quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.lang.CharSequence value) {
    this.Quantity = value;
  }

  /**
   * Gets the value of the 'UnitPrice' field.
   * @return The value of the 'UnitPrice' field.
   */
  public java.lang.CharSequence getUnitPrice() {
    return UnitPrice;
  }

  /**
   * Sets the value of the 'UnitPrice' field.
   * @param value the value to set.
   */
  public void setUnitPrice(java.lang.CharSequence value) {
    this.UnitPrice = value;
  }

  /**
   * Creates a new ClickRecord RecordBuilder.
   * @return A new ClickRecord RecordBuilder
   */
  public static ClickRecord.Builder newBuilder() {
    return new ClickRecord.Builder();
  }

  /**
   * Creates a new ClickRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClickRecord RecordBuilder
   */
  public static ClickRecord.Builder newBuilder(ClickRecord.Builder other) {
    return new ClickRecord.Builder(other);
  }

  /**
   * Creates a new ClickRecord RecordBuilder by copying an existing ClickRecord instance.
   * @param other The existing instance to copy.
   * @return A new ClickRecord RecordBuilder
   */
  public static ClickRecord.Builder newBuilder(ClickRecord other) {
    return new ClickRecord.Builder(other);
  }

  /**
   * RecordBuilder for ClickRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClickRecord>
    implements org.apache.avro.data.RecordBuilder<ClickRecord> {

    private java.lang.CharSequence Description;
    private java.lang.CharSequence Quantity;
    private java.lang.CharSequence UnitPrice;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ClickRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Description)) {
        this.Description = data().deepCopy(fields()[0].schema(), other.Description);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Quantity)) {
        this.Quantity = data().deepCopy(fields()[1].schema(), other.Quantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.UnitPrice)) {
        this.UnitPrice = data().deepCopy(fields()[2].schema(), other.UnitPrice);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ClickRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(ClickRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Description)) {
        this.Description = data().deepCopy(fields()[0].schema(), other.Description);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Quantity)) {
        this.Quantity = data().deepCopy(fields()[1].schema(), other.Quantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.UnitPrice)) {
        this.UnitPrice = data().deepCopy(fields()[2].schema(), other.UnitPrice);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'Description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return Description;
    }

    /**
      * Sets the value of the 'Description' field.
      * @param value The value of 'Description'.
      * @return This builder.
      */
    public ClickRecord.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Description = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Description' field has been set.
      * @return True if the 'Description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Description' field.
      * @return This builder.
      */
    public ClickRecord.Builder clearDescription() {
      Description = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Quantity' field.
      * @return The value.
      */
    public java.lang.CharSequence getQuantity() {
      return Quantity;
    }

    /**
      * Sets the value of the 'Quantity' field.
      * @param value The value of 'Quantity'.
      * @return This builder.
      */
    public ClickRecord.Builder setQuantity(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Quantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Quantity' field has been set.
      * @return True if the 'Quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Quantity' field.
      * @return This builder.
      */
    public ClickRecord.Builder clearQuantity() {
      Quantity = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'UnitPrice' field.
      * @return The value.
      */
    public java.lang.CharSequence getUnitPrice() {
      return UnitPrice;
    }

    /**
      * Sets the value of the 'UnitPrice' field.
      * @param value The value of 'UnitPrice'.
      * @return This builder.
      */
    public ClickRecord.Builder setUnitPrice(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.UnitPrice = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'UnitPrice' field has been set.
      * @return True if the 'UnitPrice' field has been set, false otherwise.
      */
    public boolean hasUnitPrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'UnitPrice' field.
      * @return This builder.
      */
    public ClickRecord.Builder clearUnitPrice() {
      UnitPrice = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClickRecord build() {
      try {
        ClickRecord record = new ClickRecord();
        record.Description = fieldSetFlags()[0] ? this.Description : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Quantity = fieldSetFlags()[1] ? this.Quantity : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.UnitPrice = fieldSetFlags()[2] ? this.UnitPrice : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClickRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClickRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClickRecord>
    READER$ = (org.apache.avro.io.DatumReader<ClickRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
